spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.postgreSQLDialect

# ---- GOOGLE ----
google.client.id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# ---- FACEBOOK ----
spring.security.oauth2.client.registration.facebook.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.scope=email,public_profilek

# postgresql://alfredpostgresql_peko_user:cHtH4y31y13AqRt72Yh5NBgtV1BDsch1@dpg-d6f3c3a4d50c73e4ce9g-a/alfredpostgresql_peko