spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/videodb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:alfred3000}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:Root}
cloudinary.api-key=${CLOUDINARY_API_KEY:758631993877389}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:KnhFZ8V6eaGOXu5qo97TH-R92_c}


