spring.application.name=backend
spring.datasource.url=jdbc:postgresql://dpg-d5r6qfv5r7bs73915t50-a.virginia-postgres.render.com:5432/alfredpostgresql
spring.datasource.username=alfredpostgresql_user
spring.datasource.password=uaJRcMCMcdwewV1H1I23wYjayqaORvsK
#postgresql://alfredpostgresql_user:uaJRcMCMcdwewV1H1I23wYjayqaORvsK@dpg-d5r6qfv5r7bs73915t50-a.virginia-postgres.render.com/alfredpostgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# ---- GOOGLE ----
spring.security.oauth2.client.registration.google.client-id=dod7eedco8lduo20553c08msua48ffj3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# ---- FACEBOOK ----
spring.security.oauth2.client.registration.facebook.client-id=1488321612646087
spring.security.oauth2.client.registration.facebook.client-secret=e1e4ef36b01165883e73922cbae10eac
spring.security.oauth2.client.registration.facebook.scope=email,public_profile


logging.level.root=INFO
logging.level.org.springframework.security=INFO
